version: '3'

services:
  postgres:
    container_name: radeoh-postgres
    image: postgres:12-alpine
    restart: always
    networks:
      - radeoh-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=radeoh
      - POSTGRES_PASSWORD=secret


  redis:
    container_name: radeoh-redis
    image: redis:6-alpine
    restart: always
    networks:
      - radeoh-net
    ports:
      - 6379:6379

  mailhog:
    container_name: radeoh-mailhog
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - radeoh-net
    ports:
      - 1025:1025
      - 8025:8025

networks:
  radeoh-net:
